services:
  grafana:
    user: root
    container_name: 'acme-dynamicscenes-app'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/acme-dynamicscenes-app
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/acme-dynamicscenes-app
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.acme-dynamicscenes-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: acme-dynamicscenes-app
    links:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
