apiVersion: 1

datasources:
  - name: gdev-testdata
    isDefault: false
    type: testdata
  - name: prometheus
    uid: prometheus
    type: prometheus
    isDefault: false
    access: proxy
    url: http://prometheus:9090
